### ISSUE TITLE
Copy for what happens when someone clicks 'sign the pledge'

### ISSUE THREAD

**Issue by meganrm** [townhallproject/THP-Pledge#2]

**Comment by nathanmwilliams** [comment]
Town Hall Project invites every candidate for office in 2018 to take the #TownHallPledge to the people of their district or state. This simple commitment of a minimum of four town halls per year is a clear way to say: "I will always listen to the people I work for."

See pledge forms here. Feel free to email signed pledges to info@townhallproject.com and/or tweet a photo of your candidate holding the signed pledge.

Thank you for your commitment to accessibility!

**Comment by nathanmwilliams** [comment]
[THP_Pledge State and Local.pdf](https://github.com/townhallproject/THP-Pledge/files/2024590/THP_Pledge.State.and.Local.pdf)
[Uploading THP_Pledge_House.pdf…]()
