### ISSUE TITLE
Legend for purple, gold, (and eventually red--if we add MM districts)

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/THP-Pledge#44]
Let me know if you need legend copy.

**Comment by meganrm** [comment]
<img width="1003" alt="screenshot 2018-09-21 16 41 56" src="https://user-images.githubusercontent.com/5170636/45910378-5b1e9680-bdbd-11e8-9978-7487185e736e.png">

**Comment by meganrm** [comment]
let me know what you think @nathanmwilliams

**Comment by nathanmwilliams** [comment]
-Colors on map look great. 

-The legend colors don't seem to match 100%. DYJD District on legend seems darker/oranger. Statewide pledger on legend seems a more saturated purple.

-Adjusted legend copy:

"**Do Your Job** State"

"Statewide **Town Hall Pledge**"

"**Do Your Job** District"

"U.S. House **Town Hall Pledge**"

-Any idea why NY is outlined as a Statewide pledge state? I don't think we had any, even in the primary.

-Definitely default view on this should be Nominees, otherwise will be confusing for most folks.
