### ISSUE TITLE
Continued Minnesota senate error

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/THP-Pledge#55]
Amy Klobuchar and Tim Newberger (her opponent) not listed together.

![klobuchar error](https://user-images.githubusercontent.com/25805849/47052206-42a36100-d15c-11e8-99e2-4d058a5ab487.png)

**Comment by meganrm** [comment]
There were some spaces in the google doc after "sen" in one and not the other, and I didnt clean white space off...But I deleted them and it should fix this
