### ISSUE TITLE
Amend Pledge top banner copy

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/THP-Pledge#67]
The Town Hall Pledge

In 2018 we asked every single candidate for public officeto take the #TownHallPledge to their constituents to hold a minimum of four town hall meetings per year in office.

[XX] candidates took the Pledge and won! 

But it's never too late to make this common-sense commitment to listen to the people. Ask lawmakers in your community to take the Pledge today!

**Comment by meganrm** [comment]
I did it slightly differently, I put the '[XX] candidates took the Pledge and won!' in the search bar based on the filter status
