### ISSUE TITLE
Remove deleted Pledge entries

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/THP-Pledge#82]
Right now it appears deleted entries from the Pledge / Elections doc don't disappear from the site.

E.g Diel and Amatul-Wadud here.
![deleting pledge](https://user-images.githubusercontent.com/25805849/91211049-f9f75000-e6c2-11ea-853f-09bb85c7d597.png)

**Comment by meganrm** [comment]
yeah, I don't think we ever set up delete. Is this something you expect to need to do a lot?

**Comment by nathanmwilliams** [comment]
It looks like a bunch of 2018 folks got moved over who aren't actually running this cycle. So probably a few more to come in the next day or so, but hopefully relatively few rate of errors after that. 

Simplest to just let you know when I've corrected the current data?

**Comment by nathanmwilliams** [comment]
Not in the WV 2020 tab but Joe Manchin is showing up as a 2020 Pledger for some reason.
![manchin err](https://user-images.githubusercontent.com/25805849/91216551-0384b600-e6cb-11ea-88a4-edad7290d6e1.png)

**Comment by nathanmwilliams** [comment]
Oh and how do we want to differentiate the two GA-Sen races? Make one "Sen-special"?
![GA-Sen](https://user-images.githubusercontent.com/25805849/91218263-a2aaad00-e6cd-11ea-8d42-17fbc12a7b15.png)

**Comment by meganrm** [comment]
yes, Sen-special is good

**Comment by nathanmwilliams** [comment]
Okay, I've finished updating the 2020 candidates and data, at least for the time being.

Possible to refresh everything displaying on the site, and add all Nominees?

**Comment by meganrm** [comment]
I deleted everythign and re-ran the script
